from src.games.battleship import Battleship
from src.games.bulls_and_cows import BullsAndCows
from src.games.card_trick import CardTrick
from src.games.connect_four import ConnectFour
from src.games.hangman import Hangman
from src.games.minesweeper import Minesweeper
from src.games.no_thanks import NoThanks
from src.games.tetris import Tetris
from src.games.tic_tac_toe import TicTacToe
from src.games.uno import Uno
